//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public System.DateTime Birthday { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual PassengerTypes PassengerTypes { get; set; }
    }
}
